### PR TITLE
Use the official Tomcat image as base; update Orbeon to 2019.2

### PR DESCRIPTION
**Pull request by rimas-kudelis**
I was trying out Orbeon Forms this weekend and updated your Dockerfile to use the latest version of OF in the process. I also switched it to use the official Tomcat image as base, although this could easily be changed back to use yours if you feel like maintaining it.

### CODE REVIEW

**Comment by tiredofit** [comment]
Thanks for this! I will accept the pull so that its up to date and people can test out Orbeon. It's not suitable for my needs but maybe it can give someone else the ability to check out its features!

**Comment by rimas-kudelis** [comment]
I'm in a similar situation actually.
It seems like if you need dynamic dropdown values in Orbeon, you have to use a separate web service to get these values. It's understandable if these values are indeed changing or plenty, but if you only need a simple "drill-down" question, creating a web service just to return these predefined values seems like an overkill. That's where I stopped my testing...

If you were looking for a survey platform, what did you end up using?

**Comment by tiredofit** [comment]
We're using Lime Survey for pure surveys, and then my developers are working with Form.IO for integrating data collection and display inside of applications. We used the Hsoted version for Form.IO with great success for many years for one off forms integrated into other applications. This might just be what you are after as well?

**Comment by rimas-kudelis** [comment]
I actually tried out LimeSurvey before testing Orbeon. To me, it seems rather powerful, but also lacking a few things AND buggy.
What I found lacking:
 - putting questions in a matrix
 - filtering select values by the selected value of a different field
What I found buggy:
 - frontend validation: a text field kept validating phone number as an integer and failing upon encountering the + prefix if it was the only non-digit in the value. LS guys said this shouldn't be happening since it's not a number field in the first place, but it was happening for me.
 - question show/hide logic: the form I'm currently working on has a bunch of fields which have to be shown/hidden depending on the values of other fields (this is partly due to the lack of drill-down filtering), and it didn't quite work as expected after I set all conditions.

Then there's overall slowness, but that I could live with, if everything else worked.

I'll have a look at form.io, thanks! So far, what I liked the most is SurveyJS. The only thing I didn't like about their service is how it exports matrix and file fields into CSV (as JSON structures). And the fact that their library is JS-only (so no quick and reliable way to validate or process/interpret submitted data in PHP, for example), but other than that, they're super cool. :)

**Pull request merged**
